N_CLUSTERS = 5
N_REPRESENTING_PHRASES = 3
KEYPHRASE = True
TIME_DISTANCE_CONST = 0.05
MTLS_DISTANCE_CONST = 0.3 #find proper value
DO_EXEC_LOG = True # execution log to console
DO_DATA_LOG = True # log of data to file as executing through the algorithem
DBSCAN_EPSILON_1 = 1.2
DBSCAN_MINPOINT_1 = 2
DBSCAN_EPSILON_2 = 1.2
DBSCAN_MINPOINT_2 = 2