
N_REPRESENTING_PHRASES = 3

INITIAL_KMEANS_TIMLINE_MULTIPLIER = 5

N_TIMELINES = 3
DATASET_NUMBER = 5

KEYPHRASE = True

TIME_DISTANCE_CONST = 0.05
MTLS_DISTANCE_CONST = 0.3 #find proper value

CLUSTER_DISTANCE_CONST = 0.4 #find proper value

DO_EXEC_LOG = True # execution log to console
DO_DATA_LOG = True # log of data to file as executing through the algorithem

# DBSCAN_EPSILON_1 = 0.4
DBSCAN_MINPOINT_1 = 5

# DBSCAN_EPSILON_2 = 1.2
DBSCAN_MINPOINT_2 = 5


LARGE_DIST_VALUE = 100