INPUT_PATH = 'test_io/input.txt'
OUTPUT_PATH_0 = 'test_io/output_test.txt'
OUTPUT_PATH_0_2 = 'test_io/output_test2.txt'
OUTPUT_PATH_1 = 'test_io/output.txt'
OUTPUT_PATH_2 = 'test_io/output_HT.txt'
OUTPUT_PATH_3 = 'test_io/output_SB.txt'
OUTPUT_PATH_4 = 'test_io/output_km.txt'
OUTPUT_PATH_5 = 'test_io\\output_Dataframe.html'