INPUT_PATH = 'IO/input.txt'
OUTPUT_PATH_0 = 'IO/output_test.txt'
OUTPUT_PATH_0_2 = 'IO/output_test2.txt'
OUTPUT_PATH_1 = 'IO/output.txt'
OUTPUT_PATH_2 = 'IO/output_HT.txt'
OUTPUT_PATH_3 = 'IO/output_SB.txt'
OUTPUT_PATH_4 = 'IO/output_km.txt'
OUTPUT_PATH_5 = 'IO\\output_Dataframe.html'